### PR TITLE
Fix-up support for TinyFPGA B2 board

### PR DESCRIPTION
**Pull request by nathanrossi**
This pull request sets up the TinyFPGA B2 board support based on the existing TinyFPGA BX support with minor modifications.

Whilst this pull request does successfully build a bitstream it does not appear to work correctly or meet timing based on icetime without the fixes in #21:
```
Timing estimate: 1000011.86 ns (0.00 MHz)
```

In addition to the setup of the bitstream this pull request also includes building a full SPI flash image which contains the "bootmeta" information for the programmer. ~~However to avoid writing to the security pages, included are additional changes for the programmer to allow it to fallback to using the address map provided in the SPI flash without having the "bootmeta" information directly.~~

### CODE REVIEW

**Comment by mithro** [comment]
@nathanrossi What is the status of this so far? I would love to merge it...

**Comment by nathanrossi** [comment]
@mithro At the time of making the pull request the bootloader was functional. However it needed the fixes covered in #21 in order to synthesise, place and route correctly (at least with yosys/arachne). Though this might have changed since with yosys and arachne-pnr/nextpnr updates. I can rebase the request and test it with recent tools and see which changes from #21 are needed to get it building, or were you more interested in the tinyprog changes? If so I can split them off into a separate pull request.

**Comment by mithro** [comment]
@nathanrossi I'm interested in getting everything in here merged but you might be right in that it makes sense to split this up into multiple pull requests?

**Comment by mithro** [comment]
@nathanrossi Basically want to obsolete / remove the older tinyfpgab tool.

**Comment by nathanrossi** [comment]
@mithro So I rebased and retested the changes, with #21 merged everything works correctly with both arachne and nextpnr.

I also split off the tinyprog changes to #41.

**Pull request merged**
